version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
    - 3.8.0
  - dependency-name: org.antlr:antlr4-maven-plugin
    versions:
    - 4.9.1
  - dependency-name: org.antlr:antlr4-runtime
    versions:
    - 4.9.1
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
  - dependency-name: org.asciidoctor:asciidoctorj
    versions:
    - 2.4.2
  - dependency-name: xerces:xercesImpl
    versions:
    - 2.12.0
  - dependency-name: org.webjars.bower:jquery
    versions:
    - 3.5.1
  - dependency-name: org.freemarker:freemarker
    versions:
    - 2.3.30
